project:
  type: website
  output-dir: docs

website:
  title: "Julia Marcinkowska"
  description: Julia's website
  favicon: "/images/A ball.png"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
    right:
      - icon: github
        href: https://github.com/juliam98/
        aria-label: GitHub
      - contact.qmd
    logo: "/images/A ball.png"
    lightbox: false
  open-graph: 
    title: "Julia's website"
    description: "This is Julia's website"
    image: images/ivegotacomputer.jpg
    image-alt: "Image of corvax"
  twitter-card:
    creator: "JuliaMa_98"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true
    footnotes-hover: true



