"use strict";loaded_1_7(function(_){var window=this;
_.k("d6FVZd");

_.l();
_.k("yb08jf");
var wMc,yMc;wMc=function(a,b,c){const d=a.Ga++;if(a.oa===void 0)return d;b=b instanceof _.gp?b.toArray():[b];a.Aa.push({key:d,elements:b,callback:c});b.forEach(e=>{a.oa.observe(e)});return d};_.xMc=function(a,b){if(a.oa!==void 0){var c=a.Aa.filter(d=>d.key===b).flatMap(d=>d.elements);a.Aa=a.Aa.filter(d=>d.key!==b);c.filter(d=>!a.Aa.flatMap(e=>e.elements).includes(d)).forEach(d=>{a.oa.unobserve(d)})}};
yMc=class{constructor(){this.Aa=[];this.Ga=1;const a=window;this.oa=a.ResizeObserver===void 0?void 0:new a.ResizeObserver(b=>{this.Ea(b)})}pause(){this.oa!==void 0&&this.oa.disconnect()}resume(){this.oa!==void 0&&this.Aa.flatMap(a=>a.elements).forEach(a=>{this.oa.observe(a)})}isSupported(){return this.oa!==void 0}Ea(a){this.Aa.forEach(b=>{const c=a.filter(d=>b.elements.includes(d.target));c.length>0&&b.callback(c)})}};_.zMc=function(a,b,c){return wMc(a.oa,b,c)};_.mG=class{constructor(){this.oa=new yMc}pause(){this.oa.pause()}resume(){this.oa.resume()}isSupported(){return this.oa.isSupported()}};
_.sh(_.mG,_.Sp);
_.l();
_.k("hypYI");
_.cId=class extends _.tp{static hb(){return{service:{window:_.fv}}}constructor(a){super();this.window=a.service.window.get();this.document=a.service.window.getDocument()}oa(){return this.document.documentElement.clientWidth/this.window.innerWidth}};_.rh(_.e8a,_.cId);
_.l();
var BMc;BMc=_.Vg().getDocument().documentElement;_.AMc=BMc.requestFullscreen?"fullscreenchange":BMc.webkitRequestFullscreen?"webkitfullscreenchange":BMc.mozRequestFullScreen?"mozfullscreenchange":BMc.msRequestFullscreen?"MSFullscreenChange":"fullscreenchange";
_.CMc=function(a){a=a?a.getDocument():_.Vg().getDocument();const b=a.body;return!!(b.webkitRequestFullscreen&&a.webkitFullscreenEnabled||b.mozRequestFullScreen&&a.mozFullScreenEnabled||b.msRequestFullscreen&&a.msFullscreenEnabled||b.requestFullscreen&&a.fullscreenEnabled)};_.DMc=function(a,b){if(a.requestFullscreen)return a.requestFullscreen(b);if(a.webkitRequestFullscreen)return a.webkitRequestFullscreen();if(a.mozRequestFullScreen)return a.mozRequestFullScreen();if(a.msRequestFullscreen)return a.msRequestFullscreen()};
_.EMc=function(a){a=a?a.getDocument():_.Vg().getDocument();a.exitFullscreen?a.exitFullscreen():a.webkitCancelFullScreen?a.webkitCancelFullScreen():a.mozCancelFullScreen?a.mozCancelFullScreen():a.msExitFullscreen&&a.msExitFullscreen()};_.FMc=function(a){a=a?a.getDocument():_.Vg().getDocument();return!!(a.webkitIsFullScreen||a.mozFullScreen||a.msFullscreenElement||a.fullscreenElement)};
_.k("yGkNuf");
var GMc,JMc,QMc,RMc,SMc,TMc;GMc=function(a,b=0){return{Kl:a,ym:b}};_.HMc=function(){return!1};_.IMc=function(a){return a.Na?a.Na.querySelector("[jsname=Ehk02]")||null:null};_.KMc=function(a){return a.Sa?(a=JMc(a.Sa.hQ(),_.Mt),a?(a=JMc(a,_.mD))?_.ipc(a.Gb().getExtension(_.mD))||null:null:null):null};_.LMc=function(){return!1};_.MMc=function(){return!1};_.NMc=function(){};_.OMc=function(){};_.PMc=function(){};
JMc=function(a,b){let c;a=(a==null?void 0:(c=a.xf())==null?void 0:_.mh(c))||[];for(const d of a){let e;if((e=d.Gb())==null?0:e.hasExtension(b))return d}};_.nG=function(a,b,c){a.isInitialized()&&_.hf(a.oa,b,c)};QMc=function(a){(a=_.DMc(a,{navigationUI:"hide"}))&&a.catch(()=>{})};RMc=function(a){var b=_.IMc(a);b&&(!(b=b.getBoundingClientRect())||b.width<=0||(b=b.top,a.Rq()&&b<52&&(b=52),a.oa.style.top=`${b}px`,a.Rq()||_.LMc()||(a.oa.style.clipPath=`inset(${52-b}px 0 0 0)`)))};
SMc=function(a){!a.Ga&&a.oa&&(a.Ga=a.oa.querySelector("[jsname=yxspve]"));a.Ga||(a.Ga=a.Aa.document.body.querySelector("[jsname=yxspve]"));return a.Ga};
_.UMc=function(a){if(a.isInitialized()){var b=_.IMc(a);if(b){var c,d=(c=_.KMc(a))==null?void 0:c.Ks();if(d){document.addEventListener("visibilitychange",a.Bb);a.Ea.addEventListener?a.Ea.addEventListener("change",a.La):a.Ea.addListener&&a.Ea.addListener(a.La);_.LMc()&&a.Aa.addEventListener("resize",a.N9);c=TMc(a);var e=b.getElementsByTagName("img")[0];c<=1&&e&&(e.style.display="none");e=_.lp(b);let g;e=(e==null?void 0:(g=e.getData("ved"))==null?void 0:_.Bo(g))||null;_.nG(a,"znUj3",{Kl:{id:d||void 0,
aspectRatio:c},IZ:e||""});var f;_.nG(a,"KZOHMb",GMc({id:d||void 0,aspectRatio:c},_.du((f=_.KMc(a))==null?void 0:_.Hg(f,3))||a.Fb||0));a.oa.style.display="block";a.oa.style.height="";a.oa.style.position="fixed";a.oa.style.top=`${b.getBoundingClientRect().top}px`;a.oa.style.left=`${b.getBoundingClientRect().left}px`;a.oa.style.width=`${b.getBoundingClientRect().width}px`;a.oa.style.height=`${b.getBoundingClientRect().height}px`;a.oa.style.zIndex="1030"}}}};
_.VMc=function(a){if(a.isInitialized()){var b=_.IMc(a);b&&(b.style.height="220px");document.removeEventListener("visibilitychange",a.Bb);a.Ea.removeEventListener?a.Ea.removeEventListener("change",a.La):a.Ea.removeListener&&a.Ea.removeListener(a.La);_.LMc()&&a.Aa.removeEventListener("resize",a.N9);_.xMc(a.Tx.oa,a.Za);a.Za=0;_.nG(a,"jQntwf");_.nG(a,"iPWSJb");a.Xa&&(_.hf(a.Xa,"jQntwf"),a.Xa=null);a.oa.style.display="none";a.oa.style.removeProperty("clip-path")}};
TMc=function(a){let b;return(a=(b=_.KMc(a))==null?void 0:b.qk())?a:1.778};
_.oG=class extends _.tp{static hb(){return{service:{Tx:_.mG,xq:_.jw,window:_.fv}}}constructor(a){super();this.Za=0;this.qb=null;this.Sa=void 0;this.Lb=this.ob=this.Jj=this.Ga=this.oa=this.Xa=this.Na=null;this.Fb=0;this.Vb=()=>{const b=_.IMc(this);b&&(this.oa.style.top=`${b.getBoundingClientRect().top}px`)};this.N9=()=>{if(this.isInitialized()){var b=_.IMc(this);if(b){var c;if((c=_.KMc(this))!=null&&c.Ks()){if(_.LMc()){var d=_.IMc(this).getBoundingClientRect().width,e=this.xq.Aa().size.height;const {maxWidth:h,
maxHeight:m}={maxWidth:d,maxHeight:e};d=TMc(this);e=Math.round(h/d);e>m&&(e=m);var f;(f=SMc(this))==null||f.style.setProperty("border-radius","16px");b.style.borderRadius="16px";d<=1&&(e=Math.min(Math.round(m*.67),950));b.style.height=`${e}px`;d<=1&&(b.style.width=`${e*d}px`);this.oa.style.height=`${e}px`;this.oa.style.width=`${e*d}px`;this.oa.style.top=`${b.getBoundingClientRect().top}px`;this.oa.style.left=`${b.getBoundingClientRect().left}px`}else{f=this.Rq()?this.Db:this.Cb;c=(this.Rq()?this.Cb:
this.Db)-52;const {maxWidth:h,maxHeight:m}={maxWidth:f,maxHeight:c};f=this.Rq();var g=!f&&TMc(this)<=1?1.778:TMc(this);let n=Math.round(h/g);n>m&&(n=m);f||(n*=.9);c=n;g*=n;b.style.height=`${c}px`;b.style.width=`${g}px`;if(b=_.IMc(this))f?(this.oa.style.removeProperty("clip-path"),(d=SMc(this))==null||d.style.removeProperty("border-radius"),b.style.removeProperty("border-radius")):((e=SMc(this))==null||e.style.setProperty("border-radius","16px"),b.style.borderRadius="16px");this.oa.style.left="50%";
this.oa.style.transform="translate(-50%, 0)";this.oa.style.height=`${c}px`;this.oa.style.width=`${g}px`}_.nG(this,"ZVbNQe")}}}};this.La=()=>{this.N9();this.Rq()?(_.nG(this,"x5gMP",1),_.HMc()&&_.CMc(this.Ja)&&_.FMc(this.Ja)&&(_.nG(this,"D8UFDb"),_.EMc(this.Ja))):(_.nG(this,"x5gMP",2),!_.LMc()&&_.HMc()&&_.CMc(this.Ja)&&!_.FMc(this.Ja)&&(_.nG(this,"f2KIuf"),this.Ga&&QMc(this.Ga)));_.MMc()&&_.nG(this,"pwISFb");RMc(this)};this.xq=a.service.xq;this.Aa=a.service.window.get();this.Ja=new _.aj(this.Aa.document);
this.Ea=this.Aa.matchMedia("(orientation: portrait)");this.Tx=a.service.Tx;this.Db=Math.min(this.Aa.innerWidth,this.Aa.innerHeight);this.Cb=Math.max(this.Aa.innerWidth,this.Aa.innerHeight);this.Bb=()=>{document.visibilityState==="hidden"&&_.nG(this,"ICrPLb")}}Rq(){return this.Ea.matches&&!_.LMc()}tb(a){this.Jj=a;this.oa&&a.Ea(this).listen(()=>{RMc(this)})}scrollTo(a){this.Jj&&this.Jj.scrollTo(a)}kb(a){this.Na=a}mb(a){this.Sa=a}isInitialized(){return!!this.oa&&!!this.oa.firstChild&&(!!this.Na||!!this.Sa||
!!this.ob)}zc(){if(this.isInitialized()){var a;(a=_.KMc(this))!=null&&a.Ks()?(_.UMc(this),this.N9()):_.VMc(this)}}Rb(a){TMc(this)<=1&&a&&(a.style.height="764px")}};_.rh(_.ds,_.oG);
_.HMc=()=>!0;
_.LMc=()=>!0;
_.l();
_.kG=function(a){_.jG=a;_.hf(document.body,"MDuPYe",!a)};_.jG=!1;
_.k("BYwJlf");
_.iMc=window.agsa_ext;_.lG=()=>_.iMc&&_.iMc.getScrollTop&&_.iMc.getScrollTop()||0;_.jMc=!1;
_.l();
_.k("RBPODc");
var lMc=function(a,b){b=Math.max(b,0);let c,d;a===document.body||a===document.documentElement?(d=window.pageYOffset,c=(e,f)=>{window.scrollTo(window.pageXOffset,f.Pqa)}):(d=a.scrollTop,c=(e,f)=>{a.scrollTop=f.Pqa});return kMc(c,d,b)},kMc=function(a,b,c){const d=c-b;return(new _.IRb(200,(e,f)=>{f.Pqa=b+d*e},a)).start()};var mMc,nMc,sMc,tMc,rMc,pMc,oMc,vMc;mMc=class extends _.Ox{constructor(){super(...arguments);this.Aa=!1}};nMc=class{constructor(a){this.window=a}get(){return this.window}getDocument(){return this.window.document}find(a){return(new _.ip(this.window.document.documentElement)).find(a)}};_.qMc=function(a){let b=oMc.get(a);b||(b=new pMc(a),oMc.set(a,b));return b};
sMc=function(a,b,c=!0){return _.Ee(function*(){if(c){var d=b+_.lG();if(a.oa.scrollTop!==d)return rMc()?new Promise(e=>{a.oa.scrollTo({top:d,behavior:"smooth"});let f=0;const g=()=>{a.oa.scrollTop===d?e():f++>10?(a.oa.scrollTop=d,e()):setTimeout(g,100)};setTimeout(g,100)}):lMc(a.oa,d)}else a.oa.scrollTop=b+_.lG(),yield new Promise(e=>void setTimeout(e,0))})};tMc=function(a,b){const c=_.ev(a).kc(d=>{d=new mMc(d.scrollTop-_.lG(),d.velocity,d.oa);d.Aa=a.Aa;b(d)}).oh().build();a.Jj.oa(c);return c};
rMc=function(){return _.vi(()=>"scrollBehavior"in document.documentElement.style)()};
pMc=class{constructor(a){this.Aa=!1;let b;((b=a.constructor)==null?void 0:b.name)==="Window"?(this.Jj=new _.Px(new nMc(a)),this.oa=_.Dta(new _.aj(a.document)),_.uMc&&"scrollRestoration"in window.history&&(a.history.scrollRestoration="manual")):(this.Jj=new _.Px(a),this.oa=a)}scrollTo(a,b=!0){const c=this;return _.Ee(function*(){c.Aa=!0;yield sMc(c,a,b);c.Aa=!1})}Ea(a){const b=new vMc(this);a&&_.oi(a,b);return b}getScrollTop(){return this.Jj.getScrollTop()-_.lG()}Gw(){return this.oa.scrollTop-_.lG()}};
_.uMc=!0;oMc=new Map;vMc=class extends _.Ue{constructor(a){super();this.Jj=a;this.Wd=[]}listen(a){this.Wd.push(tMc(this.Jj,a))}yd(){for(const a of this.Wd)this.Jj.Jj.Ea(a);this.Wd=[]}};
_.uMc=!1;
_.l();
_.k("qMBFFe");
_.ikm=function(a,b){const c=a.document.documentElement,d=a.document.body;if(!_.Kt(a.Ep.oa())){b?(_.So(c,"overscrollBehaviorY",a.La),_.So(d,"overscrollBehaviorY",a.Ja),_.So(d,"overflow",a.Ga)):(a.La=_.To(c,"overscrollBehaviorY"),a.Ja=_.To(d,"overscrollBehaviorY"),a.Ga=_.To(d,"overflow"),_.So(c,"overscrollBehaviorY","none"),_.So(d,"overscrollBehaviorY","none"),_.So(d,"overflow","hidden"));a=[...a.document.querySelectorAll("#kO001e,#gsr,header"),_.cj("z1Vi9d"),_.cj("Lj9fsd")];for(const e of a)e&&_.So(e,
{visibility:b?"":"hidden"})}};
_.jkm=class extends _.tp{static hb(){return{service:{viewport:_.jw,window:_.fv,Sma:_.JVl,config:_.Sx}}}constructor(a){super();this.Cd=null;this.La=this.Ja=this.Ga="";this.oa=0;this.xq=a.service.viewport;this.Qh=a.service.window;this.Ea=a.service.Sma;this.Ep=a.service.config;this.Jj=_.qMc(this.Qh.get());this.document=this.Qh.get().document;this.Aa=_.cj("SDsPCf")||this.document.querySelector("#gsr")}Na(a=null){if(!_.Kt(this.Ep.oa()))if(a){var b=this.Aa&&this.Aa.querySelector(`[data-tbnid="${a}"] img.rg_i`);!b&&
a.startsWith("sv-")&&(b=this.Aa&&this.Aa.querySelector(`[data-tbnid="${a}"] img`));b&&(a=_.cp(b),b=this.xq.Aa().size.height,a.top&&(a.top+a.height>this.oa+b||a.top<this.oa)&&(this.oa=a.top-b/2+a.height/2),this.Jj.oa.scrollTop=this.oa+_.lG())}else this.Jj.oa.scrollTop=this.oa+_.lG()}enterBasicMode(){_.Kt(this.Ep.oa())||this.Ea.enterBasicMode()}exitBasicMode(){_.Kt(this.Ep.oa())||this.Ea.exitBasicMode()}restoreToPreviousState(){_.Kt(this.Ep.oa())||this.Ea.restoreToPreviousState()}};_.rh(_.X6a,_.jkm);
_.jkm.prototype.Na=()=>{};
_.l();
_.L3d=class extends _.bTc{constructor(a,b){super();this.open=a;this.close=b}};
_.k("ZfBJ7b");
var zlm,Alm,Blm,Clm,Dlm,Elm,Flm,Glm,Hlm,Ilm,Jlm,Klm,Llm,Mlm,Nlm,Olm;_.$Qb.prototype.Ga=_.ca(137,function(){this.state.Za.resolve();_.Jx(this.state.Vf,"uvpcot")});_.Kx.prototype.Ga=_.ca(136,function(a){let b;(b=this.oa.get(a))==null||b.Ga()});var ylm=class extends _.q{constructor(a){super(a)}};ylm.prototype.rb="mRi2Le";zlm=function(a){return _.A(a,83)};
Alm=function(a){return _.Ee(function*(){yield a.Ea;{let c;var b=(c=a.getScope((0,_.wMb)(1)))!=null?c:a.getScope((0,_.wMb)(10));b=b!=null?b:a.getScope((0,_.wMb)(4));if(!b)throw Error("ge");}return b})};Blm=function(a){let b;return(b=a.Yq)==null?void 0:_.A(b,11)};Clm=function(a,b){return _.dh(a,7,b)};Dlm=function(a,b){typeof b!=="undefined"?a.state.Vf.Qz("uvphct",b):_.Jx(a.state.Vf,"uvphct");a.state.Ja=!0;a.state.Xa.resolve()};
Elm=function(a,b){const c=a.oa.get(b);(c==null?0:c.state.Vf.oa.startTime!=null&&!c.state.Ea)?c.state.Vf.oa.startTime==null||c.state.Ea||(c.state.Ea=_.Hx(c.state.Vf.oa.elapsedTime())):a.oa.delete(b)};Flm=function(a,b){return(a=a.oa.get(b))?_.guc(a):1};Glm=function(a,b){a.window.visualViewport&&a.window.visualViewport.addEventListener("resize",b)};Hlm=function(a){let b,c;return(c=(b=a.window.visualViewport)==null?void 0:b.pageLeft)!=null?c:0};
Ilm=function(a){if(a.Ka().getData("bp").Sb()){var b=_.Kf(a.Ka().getData("bp"),0),c=a.Ata;let d,e;const f=(e=(d=c.window.visualViewport)==null?void 0:d.scale)!=null?e:c.oa();b/=Math.round(f*100)/100;a.Ka().setStyle({top:`${b}px`,height:`calc(100% - ${24+b}px)`})}_.fp(a.Ka().el())&&Hlm(a.Ata)<0&&(b=Math.abs(Hlm(a.Ata)),a.Ka().setStyle({left:`${4+b}px`}))};Jlm=function(a,b){return _.Ee(function*(){return yield _.rp(a,b.el())})};
Klm=function(a){a=new _.ip(a);a.Xb("jsname")!=="Z9MBEf"&&(a=_.Nu(a,"Z9MBEf").first());if(!a)throw Error("Kq");return a};Llm=function(a){return _.Ee(function*(){try{let b;yield(b=a.pT)==null?void 0:b.Zp()}catch(b){}})};Mlm=function(a,b){return _.Ee(function*(){const c=yield a.Kma(b);let d,e;const f=(e=c==null?void 0:(d=c.oa)==null?void 0:_.tFb(d,b.Ea||b.Aa))!=null?e:null;return{scope:c,match:f}})};
Nlm=function(a,b,c,d,e,f,g,h){return _.Ee(function*(){const m=yield _.xe(_.Hka(_.$ab,void 0,a.Gj())),n=a.ija.nj();var p,t,v;const w=(v=e==null?void 0:(p=e.qr)==null?void 0:(t=p.vk())==null?void 0:t.getViewerType())!=null?v:0;v=a.Ka().Ab();p=_.Ex(a.Xc,()=>m.render({query:b,ZMb:c,ZAb:d,LDa:e.LDa,clusterId:e.clusterId,G_:n,qea:!e.MLb,OIb:a.Ka().el().clientHeight,Kn:w,UAb:!0}),{Yc:f.Yc||void 0,QF:_.hxc()});var y=(t=f.Ga())?Flm(a.Il,t):1,z=_.fuc(_.euc(Clm(_.duc(f.Z0||a.Z0(w,f.Ku)),Blm(a.oK)),g),h);const D=
p.querySelector("[jsname=CGzTgf]");y=yield _.luc(a.raa,{Va:e.Va,lca:a.jE(),qr:e.qr,isActive:!0,Jr:z},{Oc:f.Oc||void 0,Yc:_.Sg(D,3),Kr:_.kxc(f.Kr,y),QF:_.hxc()});z="";const G=y.querySelector("[aria-label]");if(G){var M;z=(M=G.getAttribute("aria-label"))!=null?M:""}if(z.length===0&&f.yp&&(M=f.yp.querySelector("[alt], [aria-label]"))){var T,R;z=(R=(T=M.getAttribute("aria-label"))!=null?T:M.getAttribute("alt"))!=null?R:""}z.length>0?(p.setAttribute("role","dialog"),p.setAttribute("aria-label",z)):(p.setAttribute("role",
""),p.setAttribute("aria-label",""));if(T=f.MAa?y:null)T.style.visibility="hidden";D.appendChild(y);v.appendChild(p);t&&(Elm(a.Il,t),a.Il.oa.has(t),a.Il.Aa(t,D));_.Kt(a.Ep.oa())&&a.kC&&_.So(a.kC,"visibility","hidden");if(R=yield Jlm(a,Klm(p))){R.Ld({element:f.yp});var Z,ia,ma;a.W$a=(ma=(Z=e.Pe)==null?void 0:(ia=Z.Pc())==null?void 0:_.r(ia,ylm,24))!=null?ma:null;a.document.dispatchEvent(new CustomEvent("viewerOpened"));Z=_.to;a.Eca&&Z&&!a.zj.isOpen(Z)?(_.So(Z,"position","absolute"),yield a.zj.open(Z,
a.c6(f,p,t,y,T))):yield a.Lda(p,t,y,T);t&&a.Il.Ga(t);_.nj(a.kC);a.kC=p;a.pT=R;a.Ci.N9()}else _.Gb(Error("Nq"))})};Olm=function(a,b){(a=a.kC)&&_.hf(a,b.type,b.data)};
_.j$=class extends _.wh{static hb(){return{service:{chrome:_.Rx,config:_.Sx,Il:_.Kx,wY:_.wU,Yq:_.EMb,BXa:_.P0l,Tqa:_.bId,Pb:_.Ax,Vc:_.Fx,wO:_.VSb,PZa:_.jkm,stream:_.CMb,s1a:_.ouc,Nf:_.kw,window:_.fv,visualViewport:_.cId,XB:_.oG,l6:_.yMb,jH:_.$rc,overlay:_.dH},model:{hja:_.rMb}}}constructor(a){super(a.Ya);this.fTa=this.W$a=this.pT=this.kC=null;this.window=a.service.window.get();this.document=a.service.window.getDocument();this.chrome=a.service.chrome;this.Ep=a.service.config;this.RDa=a.service.Tqa;
this.jU=a.service.l6;this.oK=a.service.Yq;this.kR=a.service.wY;this.Eb=a.service.Pb;this.wO=a.service.wO;this.ija=a.model.hja;this.raa=a.service.s1a;this.Nf=a.service.Nf;this.Ci=a.service.XB;this.Cd=null;this.Xc=a.service.Vc;this.dS=a.service.PZa;this.uq=a.service.stream;this.Rfa=a.service.BXa;this.Il=a.service.Il;this.kC=(new _.gp([this.document])).find("[jsname=Z9MBEf]").el();this.Ata=a.service.visualViewport;this.nP=a.service.jH;this.zj=a.service.overlay;(this.Eca=!this.Nf.NH())||_.Ye(this.window.document.body,
"R6Slyc",()=>{this.kC&&this.Cza(this.kC)});zlm(this.Ep.oa())&&(Ilm(this),Glm(this.Ata,()=>{Ilm(this)}));this.Lh(Promise.all([this.SW(),this.UW(),this.yjb()]))}SW(){return _.Ee(function*(){})}UW(){return _.Ee(function*(){})}yjb(){const a=this;return _.Ee(function*(){a.kC&&(a.pT=yield Jlm(a,Klm(a.kC)))})}aQ(){return this.kR.aQ(this.Ka().el())}cPa(a){var b=this.nP,c=a.data.vk(),d=this.jE();a=a.data.rk();_.Zrc(b,c,d,a)}kAb(a){const b=this;return _.Ee(function*(){var c=a.data;b.fTa=c;if(!c.Ja){var d=b.uq.streams.get(c.Ku||
""),e=(d==null?void 0:d.Mh())||0,f,g=(d==null?void 0:(f=d.Aa())==null?void 0:f.length)||0;f=e>0;e=e<g-1;g=c.Aa;var h=c.Ea;if(g)if(yield Llm(b),(d=c.Ga())&&b.Il.Ea(d),b.Rfa.reset(),d=yield Mlm(b,c),d.match){var m=d.scope,n=d.match,p=n.bH;n=n.result;let t=void 0,v;if((v=n.Pe())==null?0:v.hasExtension(_.wuc))t=_.uuc(_.ol(n.Pe(),_.wuc));b.Ci.mb(t);yield Nlm(b,b.ija.nj().getQuery()||"",h||g,h?"imgdii":"imgrc",{Va:n.Xq(),clusterId:c.clusterId||p.id(),MLb:d,Pe:n.Pe(),LDa:m.id,qr:t},c,f,e);b.Ci.kb(b.Ka().el().querySelector("[jsname=CGzTgf]"))}else c=
"Viewer",b.Nf.NH()?c="Standalone Viewer":(f=(0,_.Lt)(),_.A(f,117)&&(c="IU Viewer")),f=((m=d.scope)==null?void 0:m.payload().getType())||null,_.Gb(Error("Lq`"+c+"`"+g+"`"+h+"`"+f));else c.oa&&c.Ku?(yield Llm(b),(g=c.Ga())&&b.Il.Ea(g),b.Rfa.reset(),yield _.zMb(b.uq,c.Ku),g=_.BMb(b.uq,c.Ku,c.oa),g.callback?(h=g.callback.hQ(),b.Ci.mb(g.callback),yield Nlm(b,b.ija.nj().getQuery()||"",c.oa,"vhid",{Va:h,Pe:(p=h.Gb())==null?void 0:_.ol(p,_.nn),qr:g.callback,LDa:g.stream.oa()},c,f,e),b.Ci.kb(b.Ka().el().querySelector("[jsname=CGzTgf]")),
d&&d.oa()==="regis"&&_.hf(b.document,"sGvq8c",d.kd())):_.Gb(Error("Mq`"+c.Ku+"`"+c.oa))):(c.Oc&&_.zx(b.Eb,{Oc:c.Oc}),c=_.to,b.Eca&&c?b.kC&&b.zj.close(c):b.kC&&(yield b.sIa()))}})}sIa(){const a=this;return _.Ee(function*(){_.VMc(a.Ci);var b,c;const d=a.Eca?null:_.aId(a.RDa,(c=(b=a.fTa)==null?void 0:b.Na)!=null?c:null);b=null;d&&(b=a.Rfa,c=d.el(),b.oa=c,b=_.We(d.el(),d.el(),"sTFXNd")[0]);if(a.kC){try{yield a.Cza(a.kC)}catch(e){}_.nj(a.kC);a.kC=null;a.pT=null;a.W$a=null}else a.dS.restoreToPreviousState();
b&&_.Kt(a.Ep.oa())&&b.focus()})}Kma(a){return a.Ea?(a=this.jU.Kma(a.Aa,a.Sa||""))?Promise.resolve(a):Promise.resolve(null):Alm(this.jU)}jE(){var a=this.aQ().width;var b=(_.Kt(this.Ep.oa())?0:16)-2*_.Eif();return a+b}c6(a,b,c,d,e){if(_.Kt(this.Ep.oa())){const f=_.USc(_.PSc(_.ZSc(new _.aTc,1),1,{replace:[5,7]}),127);a.yp&&_.$Sc(f,a.yp);a=f}else a=_.WSc(_.XSc(_.USc(new _.YSc,998)),2);return _.SSc(_.OSc(_.TSc(_.QSc(_.eH(a,this.Wja.bind(this)),[2]),!0),6),new Plm(()=>this.Lda(b,c,d,e),()=>this.sIa()))}Wja({eventType:a,
W8a:b}){b.then(()=>{this.pT&&this.pT.lj()});if(a===0){let c;(c=this.pT)==null||c.lL();return!0}if(!this.pT)throw Error("Oq");this.pT.Sc(5);return!1}Rj(a){Olm(this,a)}Vma(a){Olm(this,a)}hzb(){return this.pT}Lda(a,b,c,d){const e=this;return _.Ee(function*(){const f=yield Jlm(e,Klm(a));if(f){e.dS.enterBasicMode();e.Ka().Ab().style.setProperty("visibility","visible");if(d){_.hf(c,"DDMFCe");d.style.visibility="visible";f.fL.Ab().style.visibility="visible";var g,h;if((g=f.qaa)==null?0:(h=g.Ab())==null?
0:h.style)f.qaa.Ab().style.visibility="visible"}else yield f.EI();f.Tv();e.tDa();_.ikm(e.dS,!1);yield e.Hza();b&&(g=e.Il,h=g.oa.get(b),(h==null?0:h.state.Vf.oa.startTime!=null&&!h.state.Ja)?h.state.Vf.oa.startTime!=null&&!h.state.Ja&&(h.state.Ga?h.state.Ea&&Dlm(h,h.state.Ea):Dlm(h)):g.oa.delete(b));yield f.Rf();var m;e.document.dispatchEvent(new CustomEvent("viewerOpenFinished",{detail:{relatedImgViewer:f==null?void 0:(m=f.jn)==null?void 0:m.Sa()}}))}else _.Gb(Error("Pq"))})}Cza(a){const b=this;return _.Ee(function*(){_.VMc(b.Ci);
_.ikm(b.dS,!0);b.dS.restoreToPreviousState();const c=yield Jlm(b,Klm(a));if(c){_.hf(b.document,"kyj0be",!1);b.document.dispatchEvent(new CustomEvent("viewerClosed"));var d;((d=b.fTa)==null?0:d.Bga)?yield c.Sv():yield c.DI();c.Ld({element:null});yield b.Dza();_.pp(window,"attn_viewer_close",!1,null);b.Ka().Ab().style.visibility="hidden"}else _.Gb(Error("Qq"))})}Hza(){return Promise.resolve()}Dza(){return Promise.resolve()}Tma(a){Olm(this,a)}gra(){}tDa(){}Z0(a,b){b=b||"";b.indexOf("-")>0&&(b=b.substring(0,
b.indexOf("-")));return _.xuc.includes(a)||_.yuc.includes(b)}};_.j$.prototype.$wa$fJBVee=function(){return this.tDa};_.j$.prototype.$wa$zfeGSe=function(){return this.Tma};_.j$.prototype.$wa$o1YwPc=function(){return this.Dza};_.j$.prototype.$wa$H11Ahd=function(){return this.Hza};_.j$.prototype.$wa$e73z6=function(){return this.hzb};_.j$.prototype.$wa$onf9S=function(){return this.Vma};_.j$.prototype.$wa$mhSdVe=function(){return this.Rj};_.j$.prototype.$wa$mlmJSd=function(){return this.sIa};
_.j$.prototype.$wa$zQYYb=function(){return this.kAb};_.j$.prototype.$wa$C6KsF=function(){return this.cPa};_.j$.prototype.$wa$ysU6pb=function(){return this.yjb};_.j$.prototype.$wa$IaQd1e=function(){return this.UW};_.j$.prototype.$wa$npAYtf=function(){return this.SW};var Plm=class extends _.L3d{};_.Lu(_.bbb,_.j$);


_.j$.prototype.SW=function(){const a=this;return _.Ee(function*(){var b=_.Af(_.wXa,a.Gj());const c=yield _.Af(_.vXa,a.Gj());b=yield b;const d=a.Ka();a.O_=c.create(a.window,b,d)})};_.j$.prototype.$wa$npAYtf=function(){return this.SW};_.j$.prototype.Rj=()=>{};_.j$.prototype.$wa$mhSdVe=function(){return this.Rj};_.j$.prototype.gra=function(a){this.O_.gra(a)};
_.j$.prototype.Vma=function(){if(this.O_)this.O_.Vma();else{var a=this.window,b=this.Ka();a=a.innerWidth;a=a<1264?368:Math.min(368+a-1264,569);a>368?b.addClass("sUDUrf").removeClass("WdLoq"):b.addClass("WdLoq").removeClass("sUDUrf");b.setStyle("width",`${a}px`)}let c;(c=this.Ci)==null||c.N9()};_.j$.prototype.$wa$onf9S=function(){return this.Vma};_.j$.prototype.Hza=function(){if(this.O_)return this.O_.Lda();this.Ka().setStyle("display","block");return Promise.resolve()};_.j$.prototype.$wa$H11Ahd=function(){return this.Hza};
_.j$.prototype.Dza=function(){if(this.O_)return this.O_.Cza();this.Ka().setStyle("display","none");return Promise.resolve()};_.j$.prototype.$wa$o1YwPc=function(){return this.Dza};_.j$.prototype.Tma=function(){this.O_.Tma()};_.j$.prototype.$wa$zfeGSe=function(){return this.Tma};


_.l();
});
// Google Inc.
